name: interview_project
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.5.4
flutter_riverpod: ^2.6.1
flutter_screenutil: ^5.9.0+2
go_router: ^13.2.0 



dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  flutter_screenutil: ^5.9.3
  go_router: ^14.8.1
  fl_chart: ^0.64.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^5.0.0


flutter:

  
  uses-material-design: true

  